### ISSUE TITLE
Link al website della società in alcuni casi mal formattato

### ISSUE THREAD

**Issue by lorenzoperone** [ondata/opendatacompanies.eu#1]
Vedi http://opendatacompanies.eu/openmove.com
relativo a   OpenMove Italy

oppure
http://opendatacompanies.eu/www.hammer-project.com
http://opendatacompanies.eu/openmove.com

relativi a 
Wise Town 		Italy 	Website 	Source
Hammer Project 		Italy 	Website 	Source

**Comment by nelsonmau** [comment]
ora dovrebbe funzionare. Il problema era che in colonna {website} avevo scritto a mano molti indirizzi, e alcuni senza http:// davanti.
In questi casi il browser interpreta il tag `<a>` come se fosse una posizione dentro la root, e quindi c'erano molti errori.

Puoi verificare se ti sempre ok?
grazie! :)

**Comment by lorenzoperone** [comment]
A me sembra sparita la colonna sito web dell'azienda


Lorenzo Perone
Sostieni Ricostruzione Trasparente
<https://www.produzionidalbasso.com/project/ricostruzione-trasparente/>
twitter: @lorenzo_perone <https://twitter.com/lorenzo_perone>
photoblog: http://immagini.me


Il giorno 2 febbraio 2017 00:31, Andrea Nelson Mauro <
notifications@github.com> ha scritto:

**Comment by nelsonmau** [comment]
sì sì, ora il website è attaccato al nome, sto modificando proprio adesso

**Comment by nelsonmau** [comment]
fixed...
