### ISSUE TITLE
Nuova icona e nuovo colore hyperlink

### ISSUE THREAD

**Issue by aborruso** [ondata/opendatacompanies.eu#3]
Ho rimosso "Petrusino" style, and now it's

![image](https://cloud.githubusercontent.com/assets/30607/22703908/0bf46ea0-ed66-11e6-84ba-d89fce3971b7.png)

**Comment by nelsonmau** [comment]
mi è sempre piaciuto come fai la freccia negli screenshot, voglio che tu lo sappia

**Comment by aborruso** [comment]
On 8 February 2017 at 09:37, Andrea Nelson Mauro <notifications@github.com>
wrote:

> mi è sempre piaciuto come fai la freccia negli screenshot, voglio che tu
> lo sappia
>

Voglio che tu sappia che ti piacciono cose mie, che non dipendono da me. E
questo mi mette di cattivo umore

**Comment by nelsonmau** [comment]
cosa dirà l'internet delle nostre conversazioni?
riapro la issue?
